name: Deploy to CF
on:
  push:
    branches: [deploy]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls
      - run: ls ./backend
      - run: cat ./backend/manifest.yml
      - uses: elliottpope/cloudfoundry-cli-action@v6
        with:
          CF_API: ${{ secrets.CF_API }}
          USERNAME: ${{ secrets.CF_USERNAME }}
          PASSWORD: ${{ secrets.CF_PASSWORD }}
          ORG: ${{ secrets.CF_ORG }}
          SPACE: ${{ secrets.CF_SPACE }}
          COMMAND: push backend
